export const fontOptions = [
  { name: "Plus Jakarta Sans", value: "font-jakarta-sans" },
  { name: "Inter", value: "font-inter" },
  { name: "Poppins", value: "font-poppins" },
  { name: "Montserrat", value: "font-montserrat" },
  { name: "Roboto", value: "font-roboto" },
  { name: "Open Sans", value: "font-opensans" },
  { name: "Lato", value: "font-lato" },
  { name: "Oswald", value: "font-oswald" },
  { name: "Raleway", value: "font-raleway" },
  { name: "Nunito", value: "font-nunito" },
  { name: "Ubuntu", value: "font-ubuntu" },
  { name: "Playfair Display", value: "font-playfair" },
  { name: "Lora", value: "font-lora" },
  { name: "Kanit", value: "font-kanit" },
  { name: "Quicksand", value: "font-quicksand" },
  { name: "Fira Sans", value: "font-firasans" },
  { name: "Work Sans", value: "font-worksans" },
  { name: "Bebas Neue", value: "font-bebasneue" },
  { name: "Source Sans 3", value: "font-sourcesans" },
  { name: "Merriweather", value: "font-merriweather" },
  { name: "Josefin Sans", value: "font-josefinsans" },
  { name: "Arvo", value: "font-arvo" },
  { name: "Libre Baskerville", value: "font-librebaskerville" },
  { name: "Anton", value: "font-anton" },
  { name: "Dancing Script", value: "font-dancing" },
  { name: "Pacifico", value: "font-pacifico" },
  { name: "Caveat", value: "font-caveat" },
  { name: "Inconsolata", value: "font-inconsolata" },
  { name: "Comfortaa", value: "font-comfortaa" },
  { name: "Exo 2", value: "font-exo2" },
  { name: "Righteous", value: "font-righteous" },
];